package racingcar.util

import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.DisplayName
import org.junit.jupiter.api.Nested
import org.junit.jupiter.api.Test
import racingcar.constants.Constants.DUPLICATED_NAME_EXCEPTION
import racingcar.constants.Constants.INVALID_NAME_SIZE_EXCEPTION
import racingcar.constants.Constants.INVALID_NUM_OF_CARS_EXCEPTION
import racingcar.constants.Constants.INVALID_TRIAL_NUM_RANGE_EXCEPTION
import racingcar.constants.Constants.INVALID_TRIAL_NUM_TYPE_EXCEPTION
import racingcar.utils.InputValidator

@DisplayName("InputValidatorTest 클래스")
class InputValidatorTest {
    @Nested
    inner class `자동차 이름 유효성 메소드 getValidatedNames 테스트` {
        @Test
        fun `정상적으로 입력하여 문자열의 리스트를 반환`() {
            val input = "bingt,k ,@@,123 ,우테코"
            val actualOutput: List<String> = InputValidator.getValidatedNames(input)
            val expectedOutput: List<String> =
                listOf("bingt", "k", "@@", "123", "우테코")
            assertThat(actualOutput).isEqualTo(expectedOutput)
        }

        @Test
        fun `Empty인 문자열을 입력했을 때, 예외를 발생시킴`() {
            try {
                val input = ",,,,"
                InputValidator.getValidatedNames(input)
            } catch (e: IllegalArgumentException) {
                Assertions.assertEquals(
                    INVALID_NAME_SIZE_EXCEPTION,
                    e.message,
                )
            }
        }

        @Test
        fun `Blank인 문자열을 입력했을 때, 예외를 발생시킴`() {
            try {
                val input = ", ,  ,   "
                InputValidator.getValidatedNames(input)
            } catch (e: IllegalArgumentException) {
                Assertions.assertEquals(
                    INVALID_NAME_SIZE_EXCEPTION,
                    e.message,
                )
            }
        }

        @Test
        fun `중복된 값을 입력했을 때, 예외를 발생시킴`() {
            testExceptions(
                input = "kkm,kkm,kkm",
                exceptionMessage = DUPLICATED_NAME_EXCEPTION,
                getValidatedInput = InputValidator::getValidatedNames,
            )
        }

        @Test
        fun `2개 미만의 값을 입력하였을 때, 예외를 발생시킴`() {
            testExceptions(
                input = "kkm",
                exceptionMessage = INVALID_NUM_OF_CARS_EXCEPTION,
                getValidatedInput = InputValidator::getValidatedNames,
            )
        }
    }

    @Nested
    inner class `정수인지 여부를 검사하고 값을 반환하는 메서드 getIntegerOrException 테스트` {
        @Test
        fun `정상적으로 입력하여 정수를 반환`() {
            val input = "5"
            val actualOutput: Int = InputValidator.getIntegerOrException(input)
            val expectedOutput = 5
            assertThat(actualOutput).isEqualTo(expectedOutput)
        }

        @Test
        fun `시도 횟수로 숫자가 아닌 문자가 입력됐을 때, 예외를 발생시킴`() {
            testExceptions(
                input = "안녕하세요",
                exceptionMessage = INVALID_TRIAL_NUM_TYPE_EXCEPTION,
                getValidatedInput = InputValidator::getIntegerOrException,
            )
        }

        @Test
        fun `시도 횟수로 정수의 범위를 벗어나는 수가 입력됐을 때, 예외를 발생시킴`() {
            testExceptions(
                input = "2147483648",
                exceptionMessage = INVALID_TRIAL_NUM_TYPE_EXCEPTION,
                getValidatedInput = InputValidator::getIntegerOrException,
            )
        }

        @Test
        fun `시도 횟수로 float이 입력됐을 때, 예외를 발생시킴`() {
            testExceptions(
                input = "1.5",
                exceptionMessage = INVALID_TRIAL_NUM_TYPE_EXCEPTION,
                getValidatedInput = InputValidator::getIntegerOrException,
            )
        }
    }

    @Nested
    inner class `레이싱 게임 시도 횟수 유효성 메소드 getValidatedTrialNum 테스트` {
        @Test
        fun `정상적으로 입력하여 정수를 반환`() {
            val input = 5
            val actualOutput: Int = InputValidator.getValidatedTrialNum(input)
            val expectedOutput = 5
            assertThat(actualOutput).isEqualTo(expectedOutput)
        }

        @Test
        fun `시도 횟수로 0이 입력됐을 때, 예외를 발생시킴`() {
            testIntegerExceptions(
                input = 0,
                getValidatedInput = InputValidator::getValidatedTrialNum,
            )
        }

        @Test
        fun `시도 횟수로 음수가 입력됐을 때, 예외를 발생시킴`() {
            testIntegerExceptions(
                input = -5,
                getValidatedInput = InputValidator::getValidatedTrialNum,
            )
        }
    }

    private fun <T> testExceptions(
        input: String,
        exceptionMessage: String,
        getValidatedInput: (String) -> T,
    ) {
        try {
            getValidatedInput(input)
        } catch (e: IllegalArgumentException) {
            Assertions.assertEquals(exceptionMessage, e.message)
        }
    }

    private fun <T> testIntegerExceptions(
        input: Int,
        getValidatedInput: (Int) -> T,
    ) {
        try {
            getValidatedInput(input)
        } catch (e: IllegalArgumentException) {
            Assertions.assertEquals(INVALID_TRIAL_NUM_RANGE_EXCEPTION, e.message)
        }
    }
}
